name:                fallible
version:             0.1.0
homepage:            https://github.com/matsubara0507/fallible#readme
license:             BSD3
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Data
description:         Please see the README on GitHub at <https://github.com/matsubara0507/mixlogue#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- transformers

library:
  source-dirs: src

tests:
  mixlogue-test:
    main: Driver.hs
    source-dirs: test
    dependencies:
    - fallible
    - tasty
    - tasty-hspec
    other-modules: []
